import json, pathlib
d = json.load(open('scripts/size-charts/charts.json'))
charts = d['charts']
out = []
w = out.append
w("# Size charts — manual setup in Shopify admin\n")
w("Builds the per-product size-chart system without the Admin API. ~30 min, one-time.\n")
w("The Relay theme code is already wired to read this; nothing shows on the live store until Relay is published.\n")
w("\n---\n")
w("## 1. Create the metaobject definition\n")
w("Settings → Custom data → Metaobjects → **Add definition**.\n")
w("- **Name:** `Size chart`  (this sets type/handle `size_chart`)\n")
w("- Add these fields (Field key must match exactly):\n\n")
w("| Field name | Field key | Type | Notes |")
w("|---|---|---|---|")
w("| Name | `name` | Single line text | Chart title, e.g. *Summer Set (Top)* |")
w("| Unit | `unit` | Single line text | e.g. `inches` |")
w("| Note | `note` | Single line text | Optional fit note |")
w("| Data | `data` | JSON | The table (paste from section 3) |\n")
w("- Set the **entry display name** to the `name` field.\n")
w("- Save.\n")
w("\n---\n")
w("## 2. Create the product metafield\n")
w("Settings → Custom data → **Products** → Add definition.\n")
w("- **Name:** `Size charts`\n")
w("- **Namespace and key:** `custom.size_charts`  ← must be exact\n")
w("- **Type:** Metaobject → **Size chart**, and turn ON **List of entries** (so sets can show two tabs).\n")
w("- Save.\n")
w("\n---\n")
w("## 3. Create one metaobject entry per chart\n")
w("Content → Metaobjects → Size chart → **Add entry**. For each below: set **Name**, set **Unit** = `inches`, and paste the JSON into **Data**.\n")
for c in charts:
    w(f"\n### {c['name']}")
    w(f"- **Name:** `{c['name']}`")
    w(f"- **Unit:** `{c.get('unit','inches')}`")
    w("- **Data:**")
    w("```json")
    w(json.dumps(c['data'], ensure_ascii=False))
    w("```")
w("\n---\n")
w("## 4. Assign charts to products\n")
w("Use the bulk editor: Products → select all products of a style → **Edit** → add the **Size charts** column → pick the matching entry/entries. Sets get two (Top + Bottom), in order.\n\n")
w("Suggested mapping (by product title containing):\n\n")
w("| If the product is… | Assign these charts (in order) |")
w("|---|---|")
# group by match style
from collections import OrderedDict
groups = OrderedDict()
for c in charts:
    key = ', '.join(c['match'][:1])
    groups.setdefault(key, []).append(c['name'])
for key, names in groups.items():
    w(f"| “{key}” | {' + '.join(names)} |")
w("\nProducts that share measurements (e.g. every color of the Mia Dress) all point at the same single entry — create the chart once, assign to many.\n")
w("\n> The theme falls back to the existing all-sizes page for any product you haven't assigned yet, so you can migrate gradually.\n")
pathlib.Path('scripts/size-charts/SETUP.md').write_text('\n'.join(out))
print("wrote scripts/size-charts/SETUP.md", len(out), "lines")
